const { connectToDatabase } = require("../config/dbConfig");
const { Product } = require("../models/Products");
const adminId = "63a597425b7a90ceaafd7b7f";

const products = [
  {
    name: "MacBook Pro M4",
    description: "Powerful laptop for developers and designers",
    price: 120000,
    discountPrice: 115000,
    category: "Electronics",
    brand: "Apple",
    stock: 10,
    imageCover: "macbook.jpg",
    images: [],
     ratingsAverage:5,
    ratingsQuantity:280,
    createdBy: adminId,
  },
  {
    name: "iPhone 15 Pro Max",
    description: "Latest Apple flagship smartphone",
    price: 65000,
    discountPrice: 62000,
    category: "Electronics",
    brand: "Apple",
    stock: 15,
    imageCover: "iphone15.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:280,
    createdBy: adminId,
  },
  {
    name: "Samsung Galaxy S25",
    description: "Premium Android smartphone",
    price: 55000,
    discountPrice: 52000,
    category: "Electronics",
    brand: "Samsung",
    stock: 20,
    imageCover: "galaxy-s25.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:280,
    createdBy: adminId,
  },
  {
    name: "Sony WH-1000XM5",
    description: "Noise cancelling wireless headphones",
    price: 18000,
    discountPrice: 16500,
    category: "Electronics",
    brand: "Sony",
    stock: 12,
    imageCover: "sony-headphones.jpg",
    images: [],
     ratingsAverage:2.5,
    ratingsQuantity:50,
    createdBy: adminId,
  },
  {
    name: "Logitech G Pro X",
    description: "Mechanical gaming keyboard",
    price: 5500,
    discountPrice: 5000,
    category: "Electronics",
    brand: "Logitech",
    stock: 30,
    imageCover: "keyboard.jpg",
    images: [],
     ratingsAverage:1.5,
    ratingsQuantity:12,
    createdBy: adminId,
  },
  {
    name: "Nike Air Max",
    description: "Comfortable running shoes",
    price: 6500,
    discountPrice: 6000,
    category: "Fashion",
    brand: "Nike",
    stock: 25,
    imageCover: "nike-shoes.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:280,
    createdBy: adminId,
  },
  {
    name: "Adidas Ultraboost",
    description: "High performance sports shoes",
    price: 7200,
    discountPrice: 6800,
    category: "Fashion",
    brand: "Adidas",
    stock: 18,
    imageCover: "adidas-shoes.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:280,
    createdBy: adminId,
  },
  {
    name: "Puma Hoodie",
    description: "Warm and stylish hoodie",
    price: 1800,
    discountPrice: 1500,
    category: "Fashion",
    brand: "Puma",
    stock: 40,
    imageCover: "hoodi.jpg",
    images: [],
     ratingsAverage:4.0,
    ratingsQuantity:60,
    createdBy: adminId,
  },
  {
    name: "Levis Jeans",
    description: "Classic slim fit jeans",
    price: 2200,
    discountPrice: 2000,
    category: "Fashion",
    brand: "Levis",
    stock: 35,
    imageCover: "jeans.jpg",
    images: [],
     ratingsAverage:4.0,
    ratingsQuantity:280,
    createdBy: adminId,
  },
  {
    name: "Wooden Coffee Table",
    description: "Modern living room coffee table",
    price: 4500,
    discountPrice: 4200,
    category: "Home & Kitchen",
    brand: "IKEA",
    stock: 10,
    imageCover: "coffee-table.jpg",
    images: [],
     ratingsAverage:3.5,
    ratingsQuantity:80,
    createdBy: adminId,
  },
  {
    name: "Dining Chair",
    description: "Comfortable wooden dining chair",
    price: 1500,
    discountPrice: 1300,
    category: "Home & Kitchen",
    brand: "IKEA",
    stock: 20,
    imageCover: "chair.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:200,
    createdBy: adminId,
  },
  {
    name: "Cookware Set",
    description: "Non stick cookware set",
    price: 3500,
    discountPrice: 3200,
    category: "Home & Kitchen",
    brand: "Tefal",
    stock: 15,
    imageCover: "cookware.jpg",
    images: [],
     ratingsAverage:4.0,
    ratingsQuantity:60,
    createdBy: adminId,
  },
  {
    name: "L'Oreal Face Wash",
    description: "Deep cleansing face wash",
    price: 250,
    discountPrice: 220,
    category: "Beauty",
    brand: "L'Oreal",
    stock: 50,
    imageCover: "facewash.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:280,
    createdBy: adminId,
  },
  {
    name: "Maybelline Mascara",
    description: "Long lasting mascara",
    price: 450,
    discountPrice: 400,
    category: "Beauty",
    brand: "Maybelline",
    stock: 40,
    imageCover: "mascara.jpg",
    images: [],
     ratingsAverage:4.0,
    ratingsQuantity:100,
    createdBy: adminId,
  },
  {
    name: "Nivea Body Lotion",
    description: "Moisturizing body lotion",
    price: 300,
    discountPrice: 250,
    category: "Beauty",
    brand: "Nivea",
    stock: 60,
    imageCover: "lotion.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:180,
    createdBy: adminId,
  },
  {
    name: "Football",
    description: "Professional training football",
    price: 800,
    discountPrice: 700,
    category: "Sports",
    brand: "Adidas",
    stock: 25,
    imageCover: "football.jpg",
    images: [],
     ratingsAverage:3.5,
    ratingsQuantity:80,
    createdBy: adminId,
  },
  {
    name: "Yoga Mat",
    description: "Anti slip yoga mat",
    price: 650,
    discountPrice: 550,
    category: "Sports",
    brand: "Reebok",
    stock: 30,
    imageCover: "yoga-mat.jpg",
    images: [],
     ratingsAverage:4.5,
    ratingsQuantity:175,
    createdBy: adminId,
  },
  {
    name: "Dumbbells Set",
    description: "Adjustable dumbbells set",
    price: 2500,
    discountPrice: 2200,
    category: "Sports",
    brand: "Decathlon",
    stock: 12,
    imageCover: "dumbbels.jpg",
    images: [],
     ratingsAverage:4.0,
    ratingsQuantity:320,
    createdBy: adminId,
  },
  {
    name: "Clean Code",
    description: "A handbook of agile software craftsmanship",
    price: 850,
    discountPrice: 750,
    category: "Books",
    brand: "Pearson",
    stock: 20,
    imageCover: "clean-code.jpg",
    images: [],
     ratingsAverage:3.5,
    ratingsQuantity:200,
    createdBy: adminId,
  },
  {
    name: "JavaScript The Good Parts",
    description: "Classic JavaScript programming book",
    price: 600,
    discountPrice: 500,
    category: "Books",
    brand: "O'Reilly",
    stock: 15,
    imageCover: "java-book.jpg",
    images: [],
    ratingsAverage:4.5,
    ratingsQuantity:280,
    createdBy: adminId,
  },
];

async function seedProducts() {
  try {
    await connectToDatabase();

    await Product.deleteMany();

    await Product.insertMany(products);

    console.log("Products Seeded Successfully");

    process.exit(0);
  } catch (error) {
    console.log(error);

    process.exit(1);
  }
}

seedProducts();
